appointment/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.appointmentview,name="appointment"),
    path('ajax/load-consultant/',views.load_consultant,name="ajax_load_consultant"),#AJAX
]

doctor/urls.py
from django.urls import path
from .views import *
from . import views

urlpatterns = [
    path('',ConsultantView.as_view(),name="consultant"),
    path("consultantdetails",ConsultantDetailView.as_view(),name="consultantdetails")

]

healthcare/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('patient.urls')),
    path('consultant',include('doctor.urls')),
    path('appointment',include('appointment.urls')),
]

appointment/models.py

from django.db import models
from patient.models import Patient
from doctor.models import Department,Consultant
import uuid

TYPE = (
    ("Physical Visit", "Physical Visit"),
    ("Teleconsultation","Teleconsultation")
)

Time = (
    ("09.30 AM - 10.00 AM", "09.30 AM - 10.00 AM"),
    ("10.00 AM - 10.30 AM", "10.00 AM - 10.30 AM"),
    ("10.30 AM - 11.00 AM", "10.30 AM - 11.00 AM"),
    ("11.00 AM - 11.30 AM", "11.00 AM - 11.30 AM"),
    ("11.30 AM - 12.00 PM", "11.30 AM - 12.00 PM"),
    ("12.00 PM - 12.30 PM", "12.00 PM - 12.30 PM"),
    ("12.30 PM - 01.00 PM", "12.30 PM - 01.00 PM"),
)

class Appointment(models.Model):
    uid = models.UUIDField(primary_key=True,editable=False,default=uuid.uuid4)
    patient = models.ForeignKey(Patient, on_delete=models.SET_NULL, null=True, blank=True,editable=False)
    name = models.CharField(max_length=200)
    email = models.EmailField(null=True,blank=True)
    mobile =models.CharField(max_length=10)
    department = models.ForeignKey(Department, on_delete=models.SET_NULL, null=True, blank=True)
    consultant = models.ForeignKey(Consultant, on_delete=models.SET_NULL, null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True)
    timeslot = models.CharField(max_length=100,choices=Time,default="Select Time Slot")
    consultant_type = models.CharField(max_length=100,choices=TYPE,default="Select Type")
    message = models.TextField()

    def __str__(self):
        return "uuid number"+ str(self.uid)+"patient name"+ str(self.name)


appointment/forms.py
from django import forms

from .models import Appointment, Consultant


class AppointmentForm(forms.ModelForm):
    class Meta:
        model = Appointment
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['consultant'].queryset = Consultant.objects.none()

        if 'department' in self.data:
            try:
                department_id = int(self.data.get('department'))
                self.fields['consultant'].queryset = Consultant.objects.filter(department_id=department_id).order_by('name')
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        elif self.instance.pk:
            self.fields['consultant'].queryset = self.instance.department.counsltant_set.order_by('name')

appointment/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .forms import AppointmentForm
from doctor.models import Consultant

def appointmentview(request):
    form = AppointmentForm()
    if request.method == 'POST':
        form = AppointmentForm(request.POST)
        if form.is_valid():
            form.save()

        return redirect("home")

    return render(request,"appointment.html",{'form':form})

    
#AJAX
def load_consultant(request):
    department_id = request.GET.get('department_id')
    consults = Consultant.objects.filter(department_id=department_id).all()
    return render(request,'consultname.html',{'consults':consults})

appointment/templates/appointment.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Dependent Dropdown in Django</title>
</head>
<body>
<h2>Person Form</h2>

<form method="post" id="appointForm" data-consultant-url="{% url 'ajax_load_consultant' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
</form>

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
    $("#id_department").change(function () {
        const url = $("#appointForm").attr("data-consultant-url");  // get the url of the `load_cities` view
        const departmentId = $(this).val();  // get the selected country ID from the HTML input

        $.ajax({                       // initialize an AJAX request
            url: url,                    // set the url of the request (= /persons/ajax/load-cities/ )
            data: {
                'department_id': departmentId       // add the country id to the GET parameters
            },
            success: function (data) {   // `data` is the return of the `load_cities` view function
                $("#id_consultant").html(data);  // replace the contents of the city input with the data that came from the server
                /*

                let html_data = '<option value="">---------</option>';
                data.forEach(function (city) {
                    html_data += `<option value="${city.id}">${city.name}</option>`
                });
                console.log(html_data);
                $("#id_city").html(html_data);

                */
            }
        });

    });
</script>

</body>
</html>

appointment/templates/consultname.html
<option value="">---------</option>
{% for consult in consults %}
<option value="{{ consult.pk }}">{{ consult.name }}</option>
{% endfor %}